name: Workflow for testing

on:
  push:
  workflow_dispatch:
    inputs:
      failJob:
        description: Fail the job?
        type: boolean
        required: true
        default: false
env:
  JAR_FILE: ./target/$( mvn help:evaluate -Dexpression=project.name -q -DforceStdout )-$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout ).jar

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create tmp json file
        run: |
          tmp=$(mktemp)
          image=
          jq --arg a "$image" '.containerDefinitions[0].image = $a' task-definition.json > "$tmp" && mv "$tmp" test.json
          cat test.json

      - name: Load env variables
        uses: cardinalby/export-env-action@v1
        with:
          envFile: "variables.env"
          expand: "true"

      - name: debug
        run: echo ${{ env.IMAGE }}
